name: testnet

# typically this would only be on main / tagged releases
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
    GO_VERSION: 1.21.0
    TESTNET_FILE: "ibc-testnet" # in the chains/ dir

permissions:
  contents: read
  issues: write

# ssh -o StrictHostKeyChecking=no root@95.217.238.29

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
        # TODO: shut down any current instances?
        # if there is a current instance already running, allow for it to be stopped & re-started? (local-ic not the entire box)

      - uses: actions/checkout@v3

      - uses: TimDaub/hetzner-cloud-deploy-server-action@v2
        with:
          server-name: "gh-actions-tn-${{github.sha}}"
          server-image: "ubuntu-22.04"
          server-type: "cpx21" # shared
          # server-type: "ccx23" # dedicated
          ssh-key-name: "reece-hetzner"
          delete-server: false
          # may need to do floating IPs for shared use & static IP usage?
          startup-timeout: 40000 # ms
          # https://github.com/Reecepbcups/livetestnetchain/settings/secrets/actions/new
          hcloud-token: ${{ secrets.HCLOUD_TOKEN }}

      - uses: JasonEtco/create-an-issue@v2.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            assignees: ${{ github.actor }}
            filename: .github/testnet.md
            update_existing: true

      - run: mkdir -p ~/.ssh/ && ssh-keyscan -H $SERVER_IPV4 >> ~/.ssh/known_hosts

      - name: Set server IP & Sha
        run: |
          echo "SERVER_IPV4_ADDR=$SERVER_IPV4" >> $GITHUB_ENV
          echo "GITHUB_SHA=${{github.sha}}" >> $GITHUB_ENV

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SERVER_IPV4_ADDR }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            whoami

            sudo apt-get update
            sudo DEBIAN_FRONTEND=noninteractive apt -y install make gcc jq bison ca-certificates curl

            wget https://go.dev/dl/go1.22.1.linux-amd64.tar.gz
            sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.22.1.linux-amd64.tar.gz
            echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.bashrc
            export PATH=$PATH:/usr/local/go/bin

            sudo DEBIAN_FRONTEND=noninteractive apt-get remove -y containerd.io
            sudo DEBIAN_FRONTEND=noninteractive apt-get -y install docker.io docker-compose
            sudo apt-get update

            wget https://github.com/strangelove-ventures/interchaintest/releases/download/v8.2.0/local-ic && chmod +x local-ic
            sudo mv local-ic /usr/local/bin

      # - uses: webfactory/ssh-agent@v0.4.1
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # testnet time
      # - run: git clone https://github.com/Reecepbcups/livetestnetchain
      # sudo add-apt-repository ppa:longsleep/golang-backports -y
      # sudo DEBIAN_FRONTEND=noninteractive apt -y install make golang-1.22 gcc jq bison
      # alias go=/usr/lib/go-1.22/bin/go
      # - run: |
      #     echo "whoami: $(whoami)" # root pls
      #     sudo apt-get update
      #     sudo DEBIAN_FRONTEND=noninteractive apt -y install make gcc jq bison ca-certificates curl

      #     # Go install
      #     wget https://go.dev/dl/go1.22.1.linux-amd64.tar.gz
      #     sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.22.1.linux-amd64.tar.gz
      #     echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.bashrc
      #     export PATH=$PATH:/usr/local/go/bin

      #     # Docker.
      #     # sudo install -m 0755 -d /etc/apt/keyrings
      #     # sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      #     # sudo chmod a+r /etc/apt/keyrings/docker.asc
      #     # echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      #     # sudo DEBIAN_FRONTEND=noninteractive apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker.io

      #     sudo DEBIAN_FRONTEND=noninteractive apt-get remove -y containerd.io
      #     sudo DEBIAN_FRONTEND=noninteractive apt-get -y install docker.io docker-compose
      #     sudo apt-get update

      #     # install local-ic
      #     wget https://github.com/strangelove-ventures/interchaintest/releases/download/v8.2.0/local-ic && chmod +x local-ic
      #     sudo sudo mv local-ic /usr/bin

      #     git clone https://github.com/strangelove-ventures/heighliner.git && cd heighliner
      #     go build
      #     sudo mv heighliner /usr/bin && chmod +x /usr/bin/heighliner

      #     cd ~/

      #     # Clone
      #     git clone https://github.com/${{ github.repository }}.git chain && cd chain

      #     # builds the docker image
      #     make local-image

      #     # start the testnet (run in a screen ?)
      #     local-ic chains # just debugging
      #     sudo screen -S testnet -d -m local-ic start ${{env.TESTNET_FILE}} --api-address=0.0.0.0 --auth-key=""
      #     # sudo -u root screen -S testnet -d -m local-ic start ibc-testnet --api-address=0.0.0.0 --auth-key=""